language: R
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - jtextor/Epitope-Prediction

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  # Download thesis
  - Rscript -e 'download.file("https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  - Rscript -e 'download.file("https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf", tempfile())'

